# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'encoder_decoder.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 330)
        MainWindow.setMinimumSize(QtCore.QSize(800, 330))
        MainWindow.setMaximumSize(QtCore.QSize(800, 330))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 781, 28))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(630, 170, 161, 71))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(630, 79, 160, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.encoder = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.encoder.setObjectName("encoder")
        self.verticalLayout.addWidget(self.encoder)
        self.decoder = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.decoder.setObjectName("decoder")
        self.verticalLayout.addWidget(self.decoder)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(700, 40, 88, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setEnabled(True)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 40, 681, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 80, 611, 241))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(630, 250, 161, 71))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Введите сообщение..."))
        self.pushButton.setText(_translate("MainWindow", "Для сообщения"))
        self.encoder.setText(_translate("MainWindow", "Зашифровать"))
        self.decoder.setText(_translate("MainWindow", "Расшифровать"))
        self.pushButton_2.setText(_translate("MainWindow", "Найти"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Или введите путь к файлу..."))
        self.pushButton_3.setText(_translate("MainWindow", "Для файла"))
